{% set name = "ghc" %}
{% set version = "9.2.1" %}
{% set unixsha256 = "cd7afbca54edf9890da9f432c63366556246c85c1198e40c99df5af01c555834" %}
{% set aarch64sha256 = "676698b0b3744af80a610d9e18e40735b9cf8ec337c072d8314d85cba8af4acc" %}

package:
  name: {{ name|lower }}-alpha2
  version: {{ version }}

source:
  - url: https://downloads.haskell.org/~ghc/9.2.1-alpha2/{{ name }}-9.2.0.20210422-x86_64-apple-darwin.tar.xz   # [osx]
    folder: binary                                                                                              # [osx]
    patches:                                                                                                    # [osx]
      - 0001-Fix-dangling-ncursesw-link.patch                                                                   # [osx]
  #- url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-apple-darwin.tar.xz   # [osx]
  #  folder: binary                                                                                              # [osx]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-centos7-linux.tar.xz  # [build_platform == "linux-64"]
    folder: binary                                                                                              # [build_platform == "linux-64"]
  - url: https://downloads.haskell.org/~ghc/9.2.1-alpha2/{{ name }}-9.2.0.20210422-src.tar.xz
    folder: source
  #- url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-src.tar.xz
  # folder: source

build:
  number: 0
  skip: True  # [not unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patchelf  # [linux]
    - gnuconfig
    - gmp
    - ncurses
    - perl *
    - make
    - automake
    - autoconf
    - libtool
    - llvmdev  # [aarch64]
  host:
    - xz
    - gmp
    - ncurses
    - libffi
    - cffi

test:
  commands:
    - ghc --help

about:
  home: https://haskell.org/ghc/
  license: BSD-3-Clause 
  license_family: BSD
  license_file: binary/LICENSE
  summary: 'Glorious Glasgow Haskell Compilation System'

  doc_url: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/
  dev_url: https://github.com/ghc/ghc

extra:
  recipe-maintainers:
    - eggzilla
    - step21
